# Use official Node.js image
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy full project
COPY . .

# Expose Cloud Run port
EXPOSE 8080

# Start server
CMD ["node", "server/server.js"]
